sudo: required
dist: trusty

language: node_js
node_js:
  - node

addons:
  chrome: stable

env:
  - DISTRIBUTION=copay
  - DISTRIBUTION=bitpay

script:
  - npm run apply:$DISTRIBUTION
  - npm run test:ci
  - npm run e2e
  - npm run test:visual

after_success:
  - npx codecov